### ISSUE TITLE
😀 Welcome to Backends for Mobile Applications

### ISSUE THREAD

**Issue by tabinks** [uchicago-cloud/mpcs51033-2019-autumn#1]
Please leave a comment introducing yourself.

**Comment by tpiske22** [comment]
Hey, I'm Taylor Piske, the Salavon Studios guy. Looking forward to the quarter!

**Comment by dwzhong** [comment]
Hi, I'm Dingwen Zhong, the late coming person.

**Comment by skoop12** [comment]
Hi, I'm Sarah Koop!  I couldn't make it to the first class, but looking forward to meeting everyone next week 😀

**Comment by AvaisSherlocked** [comment]
Hi, I'm Ava Xia, the only girl in the first class. Hope we all enjoy this class!

**Comment by dululululu** [comment]
Hi, I'm Xiangda Bai. Nice to meet all of you!
