### ISSUE TITLE
API Endpoint Names

### ISSUE THREAD

**Issue by skoop12** [uchicago-cloud/mpcs51033-2019-autumn#12]
In the homework description, it mentions that the example server calls should be stuff like: 

http://--.appspot.com/<USERNAME> [GET]
http://--.appspot.com/<USERNAME>/<IMAGEID>  [GET]

But the starter code has endpoint /upload_photo and /data.  Those appear to be the endpoints that do the same thing as the above.  Should we have duplicate endpoints or is one or the other the correct way to structure it?

**Comment by tabinks** [comment]
The ones in the starter are just boilerplate to get things working. You
should rename them to match whatever API you are going to design.
