### ISSUE TITLE
Cloud Task Example

### ISSUE THREAD

**Issue by tabinks** [uchicago-cloud/mpcs51033-2019-autumn#17]
Here is the example that I went over in class. Remember to update `project`, `queue` and `location`.

```python
import datetime

from google.cloud import tasks_v2
from google.protobuf import timestamp_pb2

project = 'YOUR_PROJECT'
queue = 'YOUR_QUEUE'
location = 'us-central1'

# Create a client.
client = tasks_v2.CloudTasksClient()
# Construct the fully qualified queue name.
parent = client.queue_path(project, location, queue)

# Construct the request body.
task = {
        'app_engine_http_request': {  # Specify the type of request.
            'http_method': 'POST',
            'relative_uri': '/example_task_handler'
        }
}

# The API expects a payload of type bytes.
payload = "This is a task."
converted_payload = payload.encode()

# Add the payload to the request.
task['app_engine_http_request']['body'] = converted_payload

# Use the client to build and send the task.
response = client.create_task(parent, task)

print('Created task {}'.format(response.name))
```

Here is the `@app.route`:
```python
@app.route('/example_task_handler', methods=['POST'])
def example_task_handler():
    payload = request.get_data(as_text=True) or '(empty payload)'
    print('Received task with payload: {}'.format(payload))

    # Do something here

    return 'Printed task payload: {}'.format(payload)
```

**Comment by skoop12** [comment]
I'm having trouble triggering this task. I have added a task handler route to my application and a function to create the task. When I create the task I can see the "created task" line print to the console, but I never see the "received task". I tried adding some logging within the task handler route and also don't see those messages logged.  I've also tried to schedule the task and still don't see "received task" printed or logged.  Is there an additional step needed to trigger the task?  It's not clear to me from the Google Cloud documentation

**Comment by tabinks** [comment]
Try printing with “print” Instead of using logging. I have found this is
more reliable to track down what’s happening.

From what it sounds like, you are doing everything you need to do.

**Comment by skoop12** [comment]
I have both a print statement and a logging statement in the task route function and neither is showing up

**Comment by tabinks** [comment]
Post your code to github and I'll look at it.

**Comment by tabinks** [comment]
@skoop12 Let me know when it's up.

**Comment by skoop12** [comment]
It's up at https://github.com/uchicago-cloud/mpcs51033-2019-autumn-assignment-2-gcp-skoop12

Starting at line 162 in main.py

**Comment by tabinks** [comment]
@skoop12 Did you make any progress on this? I'm sitting down to look at it now.

**Comment by skoop12** [comment]
I have not resolved it. But happy to come in early before class tomorrow to work it out if that's easier.

**Comment by tabinks** [comment]
That's a good idea. It's difficult to debug because I have to create an entire other project to test it.
