### ISSUE TITLE
 Assignment 1 Repositories

### ISSUE THREAD

**Issue by tabinks** [uchicago-cloud/mpcs51033-2019-autumn#2]
Python 2 web app: https://classroom.github.com/a/tae_dc5f
Python 3 web app: https://classroom.github.com/a/oG0yRI1z

**Comment by tpiske22** [comment]
Did you send out links to GCP educational credits already? I was gonna wait to start the assignment till I had that all set up. Or are we okay to just go ahead and do the assignment without?

**Comment by tabinks** [comment]
I put the link in #5, but you can go ahead and do the entire assignment without actually adding them.

**Comment by skoop12** [comment]
When I try to accept the assignment for part 1, I get an error that says "Invitations for this assignment have been disabled." Is anyone else having this issue?  The part 2 repo worked for me.

**Comment by tpiske22** [comment]
I'm having the same problem.

**Comment by tabinks** [comment]
Hmmm...I’ll take a look.

**Comment by tabinks** [comment]
I think I fixed it. It works for me, but let me know if it doesn’t for you.

**Comment by tpiske22** [comment]
Yep, works for me now. Thanks!

**Comment by tpiske22** [comment]
Quick question about 1b before the deadline. Do you want us to push our env/ files to the repo? The virtual environment files for local testing. There are a whole lot of them, compared to the number of source files, and I wasn't sure whether you wanted to see that in there or not.

**Comment by tabinks** [comment]
You do not need to.

Thanks.
