### ISSUE TITLE
Mailgun Sandbox Domain

### ISSUE THREAD

**Issue by tpiske22** [uchicago-cloud/mpcs51033-2019-autumn#20]
I'm assuming we need to set up a custom, non-sandboxed Mailgun domain? I didn't really wanna give them my credit card, but it looks like Mailgun won't allow you to send emails from a sandbox domain to addresses you haven't pre-authorized (you can only authorize 5).

I'm also having trouble Mailgunning with a sandboxed domain on my mobile app. I keep getting a 401 even though my credentials are all correct and working over curl and I'm using Google's example Python code. Not sure if this is has something to do with it being a sandbox or not.

**Comment by tabinks** [comment]
Hmmm. I'll look into it.

**Comment by tabinks** [comment]
@tpiske22 There seems to have been a change in the policy regarding "free" accounts. Hold off working on this until I figure out what's going on. Same for everyone.
