### ISSUE TITLE
Entity Setup for Using Cursors

### ISSUE THREAD

**Issue by tpiske22** [uchicago-cloud/mpcs51033-2019-autumn#21]
I know the point of setting up our entities so that User's have an attribute listing their Photos instead of Photos having an attribute for their User was to make it so we don't have to query every Photo entity in the database to get a list of a User's Photos. But I don't see a way to use cursors without doing that. With the original setup, all of our queries will be for single Users and Photos, not big batches where a cursor would be useful.

Am I missing something or are you guys okay with us adding a User attribute to Photo for this part of the project?

**Comment by tabinks** [comment]
There are different ways of using cursors. Here is one way, which I would consider to be the most straightforward.

```python
# Create user (or get user if they are all ready created)
user = User(key_name='username')

# Photos parent is the user
uploaded_photo = Photo(parent=user)

# Set all properties
uploaded_photo.some_metadata = some_data
uploaded_photo.put()
```
Now, each photo has the user as the parent and the query can be constructed using this. When you query using the ancestor which will bring back all the photos for a user:

```python
# Get the user and use as the ancestor query
user = User(key_name='username')
query = client.query(kind='Photo', ancestor=user)

# Cursor fetch
query_iter = query.fetch(start_cursor=cursor, limit=5)
page = next(query_iter.pages)
photos = list(page)
next_cursor = query_iter.next_page_token
```

If you set up your datastore entities different, there are different ways of querying with cursors. If you are already pretty far along and want to use the `User` attribute for this part, that is ok with me.

**Comment by tpiske22** [comment]
Ah, I see. Sorry, I was looking right past the first slides of the lecture. Thank you for your help.
