### ISSUE TITLE
Creating Thumbnail API

### ISSUE THREAD

**Issue by skoop12** [uchicago-cloud/mpcs51033-2019-autumn#22]
Based on the Google Cloud documentation and the homework assignment description, it seems like the google.appengine.api.images package has the functionality to resize images to thumbnails like we want for this assignment.  However, this appears to be a deprecated API that only works with Python 2.  I can't get it imported in my project.  Has anyone found another API that easily resizes and stores the thumbnail URL?

**Comment by tabinks** [comment]
Yes, the `images` module was only for python 2. 

You can use PIL (python image library) to easily do this since any python library can be included in your app:
- https://www.geeksforgeeks.org/python-pil-image-resize-method/
- https://automatetheboringstuff.com/chapter17/
