### ISSUE TITLE
friendlyeats-ios not compiling

### ISSUE THREAD

**Issue by skoop12** [uchicago-cloud/mpcs51033-2019-autumn#26]
I'm trying to follow the first homework tutorial, but when I downloaded the sample project and tried to run it for the first time, it doesn't compile.  I know based on the instructions that the app should crash initially, but it says the app should compile correcly.  My build is failing for 'ARC Semantic Issue'.  Is anyone else having this problem?  I'm including a screenshot.  

<img width="269" alt="Screen Shot 2019-10-24 at 2 27 59 PM" src="https://user-images.githubusercontent.com/37815199/67518645-ceeb3c80-f66a-11e9-9673-1dcea01b7957.png">

**Comment by hbennett766** [comment]
Sanity check: you followed [step 3](https://codelabs.developers.google.com/codelabs/firestore-ios/index.html#2) verbatim? `pod update` and all that jazz?

**Comment by skoop12** [comment]
Yes I ran those three commands, closed XCode and opened the .xcworkspace file, then tried to run it.

**Comment by hbennett766** [comment]
Hmmmm it built for me. Maybe cocoapods itself is out of date on your machine?

`sudo gem install cocoapods` will update it to the latest version

If that doesn't work, are there any errors logged when you run `pod update`?

If those both don't get anywhere, start from scratch, shouldn't take too long. Wipe everything and re-clone (or just download the zip, that's what I did) and re-run `pod update`.

Lmk where this gets you

**Comment by skoop12** [comment]
Hmm I tried updating cocoapods, redowloaded and tried cloning instead and all came up with the same error. I will work on the other parts of the assignment and can show you the errors during office hours this week

**Comment by hbennett766** [comment]
Are you on the latest version of Xcode and swift?

**Comment by hbennett766** [comment]
@tabinks have you seen this error?

**Comment by skoop12** [comment]
I'm on XCode 10.2, not sure how to update my Swift version, but that was all downloaded from their code.

**Comment by hbennett766** [comment]
Ok that _might_ be what’s up. I’m on Xcode 11.

**Comment by tabinks** [comment]
It worked for me. I’m on 11 and did a Cocoapods update.

**Comment by tabinks** [comment]
Those look they’re all coming Firebase. Next thing to try...delete the pods
and do a fresh install. Maybe one of the dependencies failed.

**Comment by skoop12** [comment]
Ah I think xcode 11 resolved it, thank you!

**Comment by tabinks** [comment]
It only took a 20 gb download...sounds about right.
