### ISSUE TITLE
Structuring Data Question

### ISSUE THREAD

**Issue by skoop12** [uchicago-cloud/mpcs51033-2019-autumn#29]
I'm not sure how to best structure the messaging data for this project.  To be as flat as possible, I had structured my DB with group name on the outside, then documents of messages within (i.e. MPCS -> {autogenerated document ID} -> message contents). 

Now when I'm thinking about writing the firebase function to do some sort of message processing, I'm not sure how to write the path to monitor new messages added and trigger the function, because the path has nothing constant: 

`exports.sentimentAnalysis = functions.database.ref('/{groupName}/{documentId}')`

Does this mean the structure of my DB is too flat? Should it be something like `group_messages/{groupName}/messages/{documentID}/{message_content}`?

**Comment by tabinks** [comment]
> Does this mean the structure of my DB is too flat? Should it be something like group_messages/{groupName}/messages/{documentID}/{message_content}?

Yes, I think that you will have to have some direct (and permanent) path connection between the group and the messages that are from the group. If you have a path that is: `/{}/{}` it would match anything with this depth. 

If you wanted to keep that structure maybe you could artificially place a intermediary document collection 'placeholder': `/{}/message/{}` that would act as a filter...but then again you would be almost replicating the second structure you mentioned.

From what I have seen of Firebase, something like `group_messages/{groupName}/messages/{documentID}/{message_content}` does not seem to be too deep of a structure and is pretty consistent with what I have seen in other applications.
