### ISSUE TITLE
Apple Developer Ids

### ISSUE THREAD

**Issue by tabinks** [uchicago-cloud/mpcs51033-2019-autumn#36]
Please send me your ids ASAP. For those of you who have, I have added you and you will get an email from Apple inviting you to the team. For some reason, it can take a day. If you don't get anything by tomorrow from Apple, let me know. 

Feel free to just put your ids in the comments below.

**Comment by skoop12** [comment]
I received the email from Apple to join the UChicago developer group, but when I select that as my team in Xcode I get a warning that my account does not have permission to modify or create app IDs.

I've waited clicked "Try Again" several times but nothing changes.  Do I need to create a certificate or do anything aside from accepting the invitation and accepting the group terms and conditions? 

<img width="471" alt="Screen Shot 2019-11-06 at 12 24 20 PM" src="https://user-images.githubusercontent.com/37815199/68326269-b2023080-0090-11ea-9520-20d740d8fe9a.png">

**Comment by tabinks** [comment]
Let me look into it....

**Comment by tabinks** [comment]
Try again, I made some changes in the Apple Connect console.

If that didn't work, try creating a code signing file and see if allows you to create an app id: https://help.apple.com/developer-account/#/devbfa00fef7

**Comment by AvaisSherlocked** [comment]
> I received the email from Apple to join the UChicago developer group, but when I select that as my team in Xcode I get a warning that my account does not have permission to modify or create app IDs.
> 
> I've waited clicked "Try Again" several times but nothing changes. Do I need to create a certificate or do anything aside from accepting the invitation and accepting the group terms and conditions?
> 
> <img alt="Screen Shot 2019-11-06 at 12 24 20 PM" width="471" src="https://user-images.githubusercontent.com/37815199/68326269-b2023080-0090-11ea-9520-20d740d8fe9a.png">

I met with the same problem, and I also tried creating the CSR, but I'm still having this issue, how did you solve the problem?

**Comment by tabinks** [comment]
@AvaisSherlocked Shut down your computer and then go back and try again. Weird Xcode bug sometimes get stuck. Also, keep hitting Try Again a few times.

**Comment by AvaisSherlocked** [comment]
I have tried logging out the simulator and restart my computer, create a new project then login in simulator again. It still doesn't work. Is there any upper bound number for a developer to create containers?

**Comment by AvaisSherlocked** [comment]
I guess I have figured it out, I was wrong about the Bundle Identifier, which was not existing in CloudKit before.
