### ISSUE TITLE
Error: "No iCloud account is configured"

### ISSUE THREAD

**Issue by skoop12** [uchicago-cloud/mpcs51033-2019-autumn#39]
I've been testing my app on the simulator and it works but when I try to test on my own phone I get an error: "No iCloud account is configured" when trying to fetchUserRecordID()

My phone is logged into my iCloud account so I'm not sure what the problem is.  Has anyone come across this?

**Comment by tabinks** [comment]
That is odd. Usually it’s the other way around. Go to the cloud gate
dashboard and look to see if there are two users registered. Each user is
based on devices so it doesn’t matter if they’re the same iCloud account.
Let me know if you see two or only one.

**Comment by skoop12** [comment]
I don't see the simulator registered as a device on the account, but I can see it's printing out a UUID of _c152cb8423d1a0eb61c9c78c3b4ccff6 when I run the app on the simulator.  I think I see my personal iPhone on the account (iPhone (3)), but it still doesn't work when running on there.

**Comment by tabinks** [comment]
This will sound like terrible advice! But turn your computer off and the on
again. Sign out of iCloud on simulator first.

**Comment by skoop12** [comment]
Ok resolved it by signing out of iCloud on the phone and back in again. Thanks!
