### ISSUE TITLE
Segue from Notification to Specific Detail View Controller

### ISSUE THREAD

**Issue by skoop12** [uchicago-cloud/mpcs51033-2019-autumn#41]
I'm able to get the joke record ID from my joke of the day notification and print it out in the app delegate, but I can't figure out a good way to pass it to my view controller and segue to that specific tableview cell's detail view.  Solutions I've found online aren't working and seem kind of hacky.  Is there a standard way to pass the data from app delegate and simulate a tableview cell "click" for the specific joke record?

**Comment by tabinks** [comment]
To pass data from AppDelegate to another part of the app, I would look at
`NSNotificationCenter` (not to be confused with `UNNotificationCenter`).
This will allow you to broadcast a message to any object listening. Here is
a snippet:
https://www.hackingwithswift.com/example-code/system/how-to-post-messages-using-notificationcenter

As far as simulating a click, I would consider the follwing options:

   - Don't try to trigger the click. Instead just load up another instance
   of your JokeDetailViewController (or whatevery you have named it) as a
   modal controller. Basically reuse what you have, but just display it
   differently.
   - You can programmatically call 'segue' methods in a view controller. No
   need to fake a click.

**Comment by skoop12** [comment]
That makes more sense thank you!
