### ISSUE TITLE
Background Silent Notification iOS 13 Issues

### ISSUE THREAD

**Issue by skoop12** [uchicago-cloud/mpcs51033-2019-autumn#42]
I'm testing my app on a device running on iOS 13, and I can receive the joke of the day notifications when the app is in the background, but can't get the alert (silent) notifications when the app is in the background.  The alert notifications will display when the app is in the foreground.

I've done some research and I think maybe it's because Apple made changes to silent notifications for iOS 13, and is now requiring a header of "apns-push-type" for silent notifications to be received in the background, but I can't figure out where to set this header.  The issue might also be unrelated to this, but I can't resolve it or figure out what else might be preventing the silent notifications from arriving in the background.  Any advice? 

https://stackoverflow.com/questions/57578083/is-aws-sns-adding-apns-push-type-apns-priority-to-its-ios-push-notification-he
https://stackoverflow.com/questions/57871677/ios-13-silent-push-notifications-are-no-longer-reliable

**Comment by tabinks** [comment]
This is odd behavior. I am able to get the silent notifications in the
background without sending any additional headers. I am using the same code
in the github repo and we went through in class.

My guess is that the headers **are** being sent since the messages
originate from Apple CloudKit servers, so I think the issue may be
something else going on. I am running the latest version of Xcode and iOS
13.2 on my phone that is getting the notifications. I would try to upgrade
Xcode if you haven't yet.

Anyone else seeing this?

**Comment by skoop12** [comment]
Hmmm... I am also using the latest version of Xcode and iOS 13.2.2.  

I should note that for both notifications (joke and alert), if the app is in the background applicaiton:didReceiveRemoteNotification does not get called.  I got the alerts to display in the background for the joke of the day by putting the same code in the application:didReceive method.  Is there something else I need to add to my code to make applicaiton:didReceiveRemoteNotification receive notifications from the background?  I've basically implemented everything from your demo AppDelegate so I'm not sure what's going wrong.

**Comment by tabinks** [comment]
@skoop12 Did you make any progress on this?

`applicaiton:didReceiveRemoteNotification()`  is only called when the app is in the foreground.

`application(_:didReceiveRemoteNotification:fetchCompletionHandler:)` is called when the app is in foreground or background, but you need to have remote notifications enabled. Is it possible you do not have them enabled?

If you do, you should see something like this...

<img width="815" alt="image" src="https://user-images.githubusercontent.com/93689/69016813-b7505c80-0967-11ea-90d4-9af2d853d25f.png">

**Comment by skoop12** [comment]
I have both Background fetch and Remote notifications checked.  I have the function:```
 func application(_ application: UIApplication,
                       didReceiveRemoteNotification userInfo: [AnyHashable : Any],
                       fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {
``` defined like your example, but it does not appear to be called for either notification type.  I can get the joke of the day to display from the background using didReceive, but the silent alert notification does not get displayed and no functions get called unless the app is in the foreground.

**Comment by skoop12** [comment]
I have both background fetch and remote notifications enabled.  I have the below function implemented but it does not get called for background notifications.  I can get the joke of the day notifications to appear when the app is in the background by using the didReceive function in AppDelegate, but the silent alert notifications don't appear to be triggering any function from the background.

```
func application(_ application: UIApplication,
                       didReceiveRemoteNotification userInfo: [AnyHashable : Any],
                       fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {
```

**Comment by skoop12** [comment]
I'm also getting this runtime error that doesn't crash the app but is likely related:

Can't end BackgroundTask: no background task exists with identifier 1 (0x1), or it may have already been ended. Break in UIApplicationEndBackgroundTaskError() to debug.

I've searched online about it but haven't found any solutions that work from Stackoverflow.

**Comment by tabinks** [comment]
Are you remembering to call `completionHandler(.newData)` at the end of the closure?

```swift
func application(_ application: UIApplication,
                   didReceiveRemoteNotification userInfo: [AnyHashable : Any],
                   fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {
    
    // Get the APS notification data
    let aps = userInfo["aps"] as! [String: AnyObject]
    
    // Do Something with the content available data
    let contentAvailable = aps["content-available"] as! Int
    if contentAvailable == 1 {
      //
      completionHandler(.newData)
    } else {
      completionHandler(.noData)
    }
  }
```

**Comment by skoop12** [comment]
I do have that. My full function is:
```
func application(_ application: UIApplication,
                       didReceiveRemoteNotification userInfo: [AnyHashable : Any],
                       fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {
        
        // Get the APS notification data
        print(userInfo)
        let aps = userInfo["aps"] as! [String: AnyObject]
        
        // Do Something with the content available data
        let contentAvailable = aps["content-available"] as! Int
        if contentAvailable == 1 {
          print("APS: \(aps)")
          let cloudKitInfo = userInfo["ck"] as! [String: AnyObject]
          let recordId = cloudKitInfo["qry"]?["rid"] as! String
          let field = cloudKitInfo["qry"]?["af"] as! [String: AnyObject]
          let jokeID = field["joke"] as AnyObject
          print("JOKE OF THE DAY RECORD ID: \(String(describing: field["joke"]))")
          if field["joke"] != nil {
             NotificationCenter.default.post(name: Notification.Name("ReceivedJokeOfTheDay"), object: nil, userInfo:["joke": jokeID])
          }
         
          // A message indicates that we have a received a silent notification
          if let message = field["message"] as? String {
            print("creating here")
            local_notification_from_silent(message: message, recordId: recordId)
          }
          completionHandler(.newData)
          
        } else {
          completionHandler(.noData)
        }
      }
```
