### ISSUE TITLE
Curl POST command errors

### ISSUE THREAD

**Issue by skoop12** [uchicago-cloud/mpcs51033-2019-autumn#6]
I’m having some trouble with the curl command portion of the first assignment.  The GET command works just fine, but when I try to write POST commands I get “could not resolve host” or “the method POST is not allowed for this resource” errors.  I can’t quite figure out how to structure the curl commands for this testing.  I’ve been trying variations like: `curl -X POST http://localhost:8080/ -H 'User-Agent: curl_client' -F guestbook_name='default_guestbook' -F content='test_content'`. Does anyone have any ideas about what's wrong with my commands?

**Comment by tabinks** [comment]
Are you able to post using the web interface without any issues?

Have you tried to deploy it and then test your command there?

**Comment by skoop12** [comment]
I'm able to post to the site through the UI in both the local and deployed environments.  The command does not work on the deployed site either (I'm getting "The method POST is not allowed for this resource")

**Comment by skoop12** [comment]
Actually, I think I got it work by putting the guestbook name in the URL

**Comment by tabinks** [comment]
👍

**Comment by tpiske22** [comment]
I've been trying to get past the same issue for a couple days now and just can't seem to. I've put the guestbook_name field in the URL and still a 405, even after twenty different reconfigurations of the command. I'm able to sign the guestbook locally and on a live site using the UI. Curl just doesn't want to sign the guestbook for me.

**Comment by hbennett766** [comment]
Make sure you include `sign` in your url, e.g. `http://localhost:8080/sign?<guestbook_name>`

**Comment by tpiske22** [comment]
Thank you! *heavy sigh*
